TASK-10A: Please model the AD dataset using the SVM, Decision Tree, and Random Forest algorithms.

Please apply train test split (%75-%25) Then grid search (hyperparameter tuning) Then classification report and confusion matrix (on the test dataset) Then compare the findings from the three algorithms

In [12]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
data = pd.read_excel("Temporary_data3_Left_Right_Copy.xlsx", index_col=0)

In [13]:

y = data["CDRGLOB"]
data.drop(columns = ["CDRGLOB"], axis = 1, inplace = True)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.25, random_state=42)

In [15]:

from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

In [16]:

import warnings
warnings.filterwarnings("ignore")

In [17]:

param_grid = {'C': [0.1, 1, 10, 100],
              'gamma': [1, 0.1, 0.01, 0.001],
              'kernel': ["rbf"]}

grid = GridSearchCV(SVC(), param_grid, refit=True)
grid.fit(X_train, y_train)
grid.best_params_


grid_pred = grid.predict(X_test)
print(confusion_matrix(y_test, grid_pred))
print(classification_report(y_test, grid_pred))

[[133  50   1   0]
 [ 72  36   0   0]
 [ 28  11   0   0]
 [  7   1   0   0]]
              precision    recall  f1-score   support

           0       0.55      0.72      0.63       184
           1       0.37      0.33      0.35       108
           2       0.00      0.00      0.00        39
           3       0.00      0.00      0.00         8

    accuracy                           0.50       339
   macro avg       0.23      0.26      0.24       339
weighted avg       0.42      0.50      0.45       339



In [18]:
from sklearn.tree import DecisionTreeClassifier
     

In [19]:
params_grid =  {
    'min_samples_leaf': [1, 2, 3],
    'max_depth': [1, 2, 3],
    "min_samples_split":[1,2,3],
    "max_features": ["auto", "sqrt", "log2"]
}

grid = GridSearchCV(DecisionTreeClassifier(), params_grid, refit=True)
grid.fit(X_train, y_train)

grid.best_params_
grid_pred = grid.predict(X_test)
print(confusion_matrix(y_test, grid_pred))
print(classification_report(y_test, grid_pred))

[[150  34   0   0]
 [ 60  46   2   0]
 [  6  22  11   0]
 [  2   4   2   0]]
              precision    recall  f1-score   support

           0       0.69      0.82      0.75       184
           1       0.43      0.43      0.43       108
           2       0.73      0.28      0.41        39
           3       0.00      0.00      0.00         8

    accuracy                           0.61       339
   macro avg       0.46      0.38      0.40       339
weighted avg       0.60      0.61      0.59       339



In [20]:
from sklearn.ensemble import RandomForestClassifier


In [ ]:
param_grid = [{
    'min_samples_split':[2, 3, 4],
    'min_samples_leaf':[2, 3, 4],
    "max_depth": [10, 20, 30],
    'max_features': ['auto'],
}]

grid = GridSearchCV(RandomForestClassifier(), param_grid, refit=True)
grid.fit(X_train, y_train)
grid.best_params_
grid_pred = grid.predict(X_test)
print(confusion_matrix(y_test, grid_pred))
print(classification_report(y_test, grid_pred))